// 欄位名 → 中文 label。item 的 label 已在 `constants/i18n.ts`；這裡補 monster 與 magic。
// 來源：../tthol-line-bot/locales/zh-tw.json。

export const monsterFieldLabels: Record<string, string> = {
  id: "編號",
  name: "名稱",
  pic: "圖片",
  type: "類型",
  sub_type: "副類型",
  elemental: "屬性",
  elemental_attack: "屬性攻擊",
  level: "等級",
  hp: "血量",
  str: "外功",
  pow: "內力",
  vit: "根骨",
  dex: "技巧",
  agi: "身法",
  wis: "玄學",
  walk_speed: "跑速",
  attack_speed: "攻速",
  attack_range: "攻擊距離",
  damage_min: "最小傷害",
  damage_max: "最大傷害",
  pDamage_min: "最小內勁傷害",
  pDamage_max: "最大內勁傷害",
  extra_def: "防禦",
  magic_def: "護勁",
  base_hit: "基礎命中",
  base_dodge: "基礎閃躲",
  critical_hit: "重擊",
  uncanny_dodge: "拆招",
  fire_def: "火抗",
  water_def: "水抗",
  lightning_def: "雷抗",
  wood_def: "木抗",
  extra_status: "額外狀態",
  status_prob: "上狀態機率",
  weaken_res: "虛弱抗性",
  stun_res: "僵直抗性",
  shape_res: "形狀抗性",
  bleed_res: "出血抗性",
  drop_exp: "經驗",
  drop_money_min: "最小銀兩",
  drop_money_max: "最大銀兩",
};

export const magicFieldLabels: Record<string, string> = {
  id: "編號",
  level: "等級",
  name: "名稱",
  icon: "圖示",
  clan: "使用職業",
  clan2: "使用職業 2",
  target: "作用目標",
  help: "說明",
  range: "距離",
  spend_mp: "MP 消耗",
  spend_hp: "HP 消耗",
  break_prob: "破招機率",
  stun: "僵直時間 (ms)",
  status_param: "效果參數",
  extra_status: "額外狀態",
  time: "持續時間 (ms)",
  func_dmg: "傷害參數",
  func_dmg_p1: "傷害參數 1",
  func_dmg_p2: "傷害參數 2",
  func_dmg_p3: "傷害參數 3",
  func_dmg_p4: "傷害參數 4",
  func_dmg_p5: "傷害參數 5",
  func_hit: "命中率",
  func_hit_p1: "命中率參數",
  skill_type: "技能分類",
  teacher: "授業 NPC",
  func_case: "觸發",
  func_case_p1: "觸發參數 1",
  func_case_p2: "觸發參數 2",
  func_case_p3: "觸發參數 3",
  func_case_p4: "觸發參數 4",
  func_case_p5: "觸發參數 5",
  pk_disable: "PK 禁用",
  attrib: "元素屬性",
  status_prob: "狀態機率",
  recharge_time: "冷卻時間",
  hit_range: "命中範圍",
  cast_effect: "施放特效",
  recharge_effect: "冷卻特效",
  spend_flag: "消耗標記",
  exclude: "互斥",
  pet_id: "寵物 ID",
  confine_state: "束縛狀態",
};

export function monsterFieldLabel(key: string): string {
  return monsterFieldLabels[key] ?? key;
}

export function magicFieldLabel(key: string): string {
  return magicFieldLabels[key] ?? key;
}
