// AUTO-GENERATED by scripts/resolve-skill-picks.mjs — 不要手改
// 來源：tthol-line-bot/src/configs/advance.config.js 的 14 個進階書分類（扣除醫毒，必中無命中率參數）
// 只記技能 identity (id, name, firstLevel)；p1/target/level range 執行時從 magic 表撈。

export type SkillSchool =
  | "刀法"
  | "惡術"
  | "掌法"
  | "劍法"
  | "匕首"
  | "劍扇"
  | "靈種"
  | "劍刃"
  | "劍氣"
  | "法術"
  | "野性"
  | "禁術"
  | "戰體";

export type SkillFamily = "人族" | "曼陀羅" | "獸族";

export interface SkillPick {
  id: number;
  name: string;
  firstLevel: number;
}

export const SKILL_SCHOOL_FAMILY: Record<SkillSchool, SkillFamily> = {
  刀法: "人族",
  惡術: "人族",
  掌法: "人族",
  劍法: "人族",
  匕首: "人族",
  劍扇: "曼陀羅",
  靈種: "曼陀羅",
  劍刃: "曼陀羅",
  劍氣: "曼陀羅",
  法術: "獸族",
  野性: "獸族",
  禁術: "獸族",
  戰體: "獸族",
};

export const SKILL_PICKS: Record<SkillSchool, readonly SkillPick[]> = {
  刀法: [
    { id: 347, name: "武修羅刀", firstLevel: 1 },
    { id: 348, name: "邪靈刀法", firstLevel: 1 },
    { id: 346, name: "血殺盤刀", firstLevel: 1 },
    { id: 345, name: "刀背狂打", firstLevel: 1 },
    { id: 704, name: "刀背狂斬", firstLevel: 1 },
    { id: 705, name: "血殺屠刀", firstLevel: 1 },
    { id: 706, name: "霸修羅刀", firstLevel: 1 },
    { id: 707, name: "妖靈刀法", firstLevel: 1 },
  ],
  惡術: [
    { id: 344, name: "毒舌恐懼", firstLevel: 1 },
    { id: 342, name: "迅捷灑沙", firstLevel: 1 },
    { id: 343, name: "百針滲血", firstLevel: 1 },
    { id: 701, name: "亂影灑沙", firstLevel: 1 },
    { id: 702, name: "千瘡百孔", firstLevel: 1 },
    { id: 703, name: "毒舌亂神", firstLevel: 1 },
  ],
  掌法: [
    { id: 352, name: "霜龍吼", firstLevel: 1 },
    { id: 350, name: "蓮華掌", firstLevel: 1 },
    { id: 353, name: "萬象流雲", firstLevel: 1 },
    { id: 351, name: "荷花眾開", firstLevel: 1 },
    { id: 709, name: "蓮蒼掌", firstLevel: 1 },
    { id: 710, name: "荷花遍地", firstLevel: 1 },
    { id: 711, name: "霜龍嘯", firstLevel: 1 },
    { id: 712, name: "萬象窮蒼", firstLevel: 1 },
  ],
  劍法: [
    { id: 356, name: "斷空劍法", firstLevel: 1 },
    { id: 357, name: "舞月劍法", firstLevel: 1 },
    { id: 714, name: "落英紛飛", firstLevel: 1 },
    { id: 715, name: "裂空劍法", firstLevel: 1 },
    { id: 716, name: "醉月劍法", firstLevel: 1 },
  ],
  匕首: [
    { id: 361, name: "精準刺擊", firstLevel: 1 },
    { id: 363, name: "無間滅擊", firstLevel: 1 },
    { id: 362, name: "抹喉刺擊", firstLevel: 1 },
    { id: 720, name: "迅雷刺擊", firstLevel: 1 },
    { id: 721, name: "碎心刺擊", firstLevel: 1 },
    { id: 722, name: "幽冥刺擊", firstLevel: 1 },
  ],
  劍扇: [
    { id: 395, name: "金剛怒扇", firstLevel: 1 },
    { id: 396, name: "春扇亂舞", firstLevel: 1 },
    { id: 398, name: "袖扇神凰", firstLevel: 1 },
    { id: 397, name: "狂風怒扇", firstLevel: 1 },
    { id: 729, name: "金剛劫扇", firstLevel: 1 },
    { id: 730, name: "春扇璇舞", firstLevel: 1 },
    { id: 731, name: "風雲雷扇", firstLevel: 1 },
    { id: 732, name: "袖扇焰鳳", firstLevel: 1 },
  ],
  靈種: [
    { id: 399, name: "熾炎獸靈種", firstLevel: 1 },
    { id: 400, name: "烈焰炸裂靈種", firstLevel: 1 },
    { id: 401, name: "嗜血魔錐靈種", firstLevel: 1 },
    { id: 402, name: "荊棘蔓陀靈種", firstLevel: 1 },
    { id: 733, name: "燐焰獸靈種", firstLevel: 1 },
    { id: 734, name: "赤陽炸裂靈種", firstLevel: 1 },
    { id: 735, name: "喋血魔錐靈種", firstLevel: 1 },
    { id: 736, name: "枯藤蔓陀靈種", firstLevel: 1 },
  ],
  劍刃: [
    { id: 836, name: "雙劍凝斬", firstLevel: 1 },
    { id: 834, name: "半月狂擊", firstLevel: 1 },
    { id: 837, name: "雙劍斬碎", firstLevel: 1 },
    { id: 835, name: "絞碎劍陣", firstLevel: 1 },
    { id: 844, name: "雙劍巨斬", firstLevel: 1 },
    { id: 842, name: "半月猛擊", firstLevel: 1 },
    { id: 845, name: "雙劍裂碎", firstLevel: 1 },
    { id: 843, name: "絞滅劍陣", firstLevel: 1 },
  ],
  劍氣: [
    { id: 838, name: "雙劍合一", firstLevel: 1 },
    { id: 839, name: "囚魔劍陣", firstLevel: 1 },
    { id: 841, name: "雙劍速擊", firstLevel: 1 },
    { id: 840, name: "寒烈劍陣", firstLevel: 1 },
    { id: 846, name: "雙劍融合", firstLevel: 1 },
    { id: 847, name: "斬魔劍陣", firstLevel: 1 },
    { id: 849, name: "雙劍瞬擊", firstLevel: 1 },
    { id: 848, name: "凍焰劍陣", firstLevel: 1 },
  ],
  法術: [
    { id: 640, name: "三昧紅蓮", firstLevel: 1 },
    { id: 638, name: "煉獄狂焰", firstLevel: 1 },
    { id: 639, name: "怒火殞星", firstLevel: 1 },
    { id: 742, name: "黑淵狂焰", firstLevel: 1 },
    { id: 743, name: "怒火沸騰", firstLevel: 1 },
    { id: 744, name: "業火紅蓮", firstLevel: 1 },
  ],
  野性: [
    { id: 633, name: "斷空瞬滅", firstLevel: 1 },
    { id: 634, name: "破空九刃", firstLevel: 1 },
    { id: 636, name: "氣勁猛擊", firstLevel: 1 },
    { id: 637, name: "真焰一閃", firstLevel: 1 },
    { id: 737, name: "斷空裂地", firstLevel: 1 },
    { id: 738, name: "破空摧天", firstLevel: 1 },
    { id: 740, name: "爆裂猛擊", firstLevel: 1 },
    { id: 741, name: "虛焰一閃", firstLevel: 1 },
  ],
  禁術: [
    { id: 788, name: "凝冰咒", firstLevel: 1 },
    { id: 789, name: "凝冰炫風", firstLevel: 1 },
    { id: 790, name: "冰刺炸裂", firstLevel: 1 },
    { id: 791, name: "冰風暴", firstLevel: 1 },
    { id: 796, name: "玄冰咒", firstLevel: 1 },
    { id: 797, name: "玄冰炫風", firstLevel: 1 },
    { id: 798, name: "冰刺爆裂", firstLevel: 1 },
    { id: 799, name: "極冰風暴", firstLevel: 1 },
  ],
  戰體: [
    { id: 784, name: "破防爪擊", firstLevel: 1 },
    { id: 785, name: "泣血爪擊", firstLevel: 1 },
    { id: 786, name: "悲狼拳勁", firstLevel: 1 },
    { id: 787, name: "悲狼吞月", firstLevel: 1 },
    { id: 792, name: "破鎧爪擊", firstLevel: 1 },
    { id: 793, name: "嗜血爪擊", firstLevel: 1 },
    { id: 794, name: "孤狼拳勁", firstLevel: 1 },
    { id: 795, name: "孤狼吞月", firstLevel: 1 },
  ],
};

// 便於依族分組顯示（Select 的 OptGroup 用）
export const SKILL_FAMILY_ORDER: readonly SkillFamily[] = ["人族", "曼陀羅", "獸族"];

export const SKILL_SCHOOLS_BY_FAMILY: Record<SkillFamily, readonly SkillSchool[]> = {
  人族: ["刀法", "惡術", "掌法", "劍法", "匕首"] as const,
  曼陀羅: ["劍扇", "靈種", "劍刃", "劍氣"] as const,
  獸族: ["法術", "野性", "禁術", "戰體"] as const,
};
